import { useState } from 'react';
import { ArrowUpRight, Check, Copy, Gift, Users, WalletCards } from 'lucide-react';
import { useGetReferralSummary } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingPanel, Money, PageHeading, Panel, Shell } from '@/components/mirrorx-ui';

export default function Referrals() {
  const query = useGetReferralSummary();
  const referral = query.data;
  const [copied, setCopied] = useState(false);
  const copyInvite = async () => {
    if (!referral) return;
    try { await navigator.clipboard.writeText(`mirrorx.app/join/${referral.referralCode}`); } catch { /* clipboard can be unavailable in preview */ }
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  };
  return <Shell><PageHeading eyebrow="Network effect" title="Referrals" detail="Invite the right people. Let the ledger do the counting." />
    {query.isError ? <ErrorState onRetry={() => void query.refetch()} title="Referral data is offline" /> : query.isLoading ? <div className="grid gap-5 lg:grid-cols-2"><Panel className="p-6"><LoadingPanel rows={4} /></Panel><Panel className="p-6"><LoadingPanel rows={4} /></Panel></div> : !referral ? <EmptyState label="No referral profile yet" detail="Your invite code will appear when your account is ready." /> : <div className="space-y-5">
      <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Panel className="surface-grid relative overflow-hidden bg-[#123749] p-7 text-[#e9f7f0]" testId="card-referral-code"><div className="absolute -right-16 -top-24 size-72 rounded-full border-[28px] border-[#36d2ae]/10" /><div className="relative"><div className="flex items-center justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-[#b9f25b] text-[#123749]"><Gift size={20} /></div><span className="rounded-full border border-[#568578] px-2.5 py-1 text-[10px] uppercase tracking-[.12em] text-[#b9f25b]">Active code</span></div><p className="mt-10 text-[10px] uppercase tracking-[.2em] text-[#93b5ad]">Your invite code</p><div className="mt-2 flex items-center gap-3"><p className="mono text-3xl tracking-[-.04em]" data-testid="text-referral-code">{referral.referralCode}</p><button type="button" onClick={copyInvite} data-testid="button-copy-invite-link" className="grid size-9 place-items-center rounded-lg bg-[#234b59] text-[#b9f25b] hover:bg-[#2e5c68]">{copied ? <Check size={15} /> : <Copy size={15} />}</button></div><p className="mt-4 max-w-sm text-sm leading-6 text-[#a9c4bd]">Share your code with people who think in positions, not predictions.</p></div></Panel><Panel className="p-7" testId="card-rewards-balance"><p className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">Available rewards</p><p className="mt-5 text-4xl font-semibold tracking-[-.07em]" data-testid="text-unpaid-rewards">{referral.unpaidRewardsSol.toLocaleString()} <span className="text-lg text-muted-foreground">SOL</span></p><p className="mt-1 text-sm text-muted-foreground">Ready to withdraw</p><div className="mt-8 flex items-center justify-between border-t border-border pt-5"><div><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Lifetime earned</p><p className="mono mt-1.5 text-sm" data-testid="text-earned-rewards">{referral.rewardsEarnedSol.toLocaleString()} SOL</p></div><button type="button" disabled aria-disabled="true" title="Withdrawal action will be enabled when the request API is available" data-testid="button-withdraw-rewards" className="inline-flex cursor-not-allowed items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs font-medium text-muted-foreground opacity-60">Withdraw <ArrowUpRight size={13} /></button></div></Panel></div>
      <div className="grid gap-5 md:grid-cols-3"><Panel className="p-6" testId="card-invited-count"><div className="flex items-center gap-2 text-[#0a9977]"><Users size={16} /><span className="text-[10px] font-semibold uppercase tracking-[.15em]">Invited</span></div><p className="mt-5 text-3xl font-semibold tracking-[-.06em]" data-testid="text-invited-count">{referral.invitedCount}</p><p className="mt-1 text-xs text-muted-foreground">active connections</p></Panel><Panel className="p-6" testId="card-volume-traded"><div className="flex items-center gap-2 text-[#4770b6]"><WalletCards size={16} /><span className="text-[10px] font-semibold uppercase tracking-[.15em]">Network volume</span></div><p className="mt-5 text-3xl font-semibold tracking-[-.06em]" data-testid="text-volume-traded"><Money value={referral.volumeTraded} digits={0} /></p><p className="mt-1 text-xs text-muted-foreground">tracked through referrals</p></Panel><Panel className="p-6" testId="card-share-invite"><div className="flex items-center gap-2 text-[#bd6d2e]"><ArrowUpRight size={16} /><span className="text-[10px] font-semibold uppercase tracking-[.15em]">One good invite</span></div><p className="mt-5 text-sm font-medium">Bring your circle into focus.</p><button type="button" onClick={copyInvite} data-testid="button-share-invite" className="mt-3 inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:underline">{copied ? 'Link copied' : 'Copy invite link'} <Copy size={13} /></button></Panel></div>
      <Panel className="p-6 sm:p-7"><p className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">How rewards work</p><div className="mt-6 grid gap-6 md:grid-cols-3"><div className="flex gap-3"><span className="mono text-xs text-[#0a9977]">01</span><div><p className="text-sm font-medium">Share your code</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Your code is unique to this command center.</p></div></div><div className="flex gap-3"><span className="mono text-xs text-[#0a9977]">02</span><div><p className="text-sm font-medium">They trade</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Eligible activity is attributed automatically.</p></div></div><div className="flex gap-3"><span className="mono text-xs text-[#0a9977]">03</span><div><p className="text-sm font-medium">You earn SOL</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Rewards settle into your available balance.</p></div></div></div></Panel>
    </div>}
  </Shell>;
}