import { useState } from 'react';
import { Check, ChevronRight, Copy, LockKeyhole, MessageCircle, ShieldCheck } from 'lucide-react';
import { useGetPublicSettings } from '@workspace/api-client-react';
import { ErrorState, LoadingPanel, PageHeading, Panel, Shell } from '@/components/mirrorx-ui';

export default function Settings() {
  const query = useGetPublicSettings();
  const [locked, setLocked] = useState(false);
  const [copied, setCopied] = useState(false);
  const copySupport = async () => {
    if (!query.data?.supportHandle) return;
    try { await navigator.clipboard.writeText(query.data.supportHandle); } catch { /* clipboard can be unavailable in preview */ }
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  };
  if (locked) return <Shell><div className="mx-auto max-w-lg py-14"><Panel className="surface-grid overflow-hidden bg-[#123749] p-8 text-center text-[#e9f7f0] sm:p-12" testId="state-login"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#b9f25b] text-[#123749]"><LockKeyhole size={24} /></div><p className="mt-7 text-[10px] uppercase tracking-[.2em] text-[#93b5ad]">MirrorX access</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.06em]">Command center locked.</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[#a9c4bd]">Your view is private. Unlock this session to return to your capital map.</p><button type="button" onClick={() => setLocked(false)} data-testid="button-unlock-session" className="mt-8 inline-flex h-11 items-center justify-center rounded-xl bg-[#b9f25b] px-5 text-sm font-semibold text-[#123749] transition hover:bg-[#cdf988]">Unlock session <ChevronRight size={16} className="ml-1" /></button><p className="mt-6 text-[11px] text-[#739991]">Session protection is local to this device.</p></Panel></div></Shell>;
  return <Shell><PageHeading eyebrow="Control plane" title="Settings" detail="The small details that keep your view dependable." />
    {query.isError ? <ErrorState onRetry={() => void query.refetch()} title="Settings are offline" /> : query.isLoading ? <Panel className="p-6"><LoadingPanel rows={5} /></Panel> : query.data && <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-5"><Panel className="p-6 sm:p-7" testId="panel-account"><div className="flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">Account access</p><h2 className="mt-1 text-lg font-semibold">Private session</h2></div><span className="inline-flex items-center gap-1.5 rounded-full bg-[#e0f8ed] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.06em] text-[#087c62]"><ShieldCheck size={12} /> verified</span></div><div className="mt-7 flex items-center gap-3 rounded-xl bg-secondary p-3.5"><div className="grid size-10 place-items-center rounded-xl bg-[#b9f25b] text-sm font-bold text-[#123749]">AM</div><div><p className="text-sm font-medium">Ari M.</p><p className="mono mt-0.5 text-[11px] text-muted-foreground">0x74...e91b</p></div><span className="ml-auto text-[11px] text-[#0a9977]">Active now</span></div><button type="button" onClick={() => setLocked(true)} data-testid="button-lock-session" className="mt-5 inline-flex items-center gap-2 text-xs font-medium text-muted-foreground transition hover:text-[#a33f37]"><LockKeyhole size={14} /> Lock command center</button></Panel><Panel className="p-6 sm:p-7" testId="panel-support"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#e8eff8] text-[#4770b6]"><MessageCircle size={18} /></div><div><p className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">Need a hand?</p><h2 className="mt-1 text-lg font-semibold">Reach support</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A real person can help with account access or a transaction that needs a closer look.</p><div className="mt-5 flex items-center gap-2"><span className="mono text-sm">{query.data.supportHandle}</span><button type="button" onClick={copySupport} data-testid="button-copy-support" className="grid size-8 place-items-center rounded-lg text-muted-foreground hover:bg-secondary hover:text-primary">{copied ? <Check size={14} /> : <Copy size={14} />}</button></div></div></div></Panel></div>
      <Panel className="p-6 sm:p-7" testId="panel-withdrawal-settings"><p className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">Withdrawal rails</p><h2 className="mt-1 text-lg font-semibold">Limits & fees</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">These public settings apply whenever a withdrawal is requested.</p><div className="mt-7 divide-y divide-border">{Object.entries(query.data.minWithdrawal).map(([chain, amount]) => <div key={chain} className="flex items-center justify-between py-4 first:pt-0" data-testid={`row-min-withdrawal-${chain.toLowerCase()}`}><span className="flex items-center gap-2.5 text-sm font-medium"><span className="grid size-7 place-items-center rounded-lg bg-secondary text-[10px] font-bold text-primary">{chain.slice(0, 1)}</span> Minimum {chain}</span><span className="mono text-sm">{amount} {chain}</span></div>)}<div className="flex items-center justify-between py-4"><span className="text-sm font-medium">Network fee</span><span className="mono text-sm text-[#0a9977]">{query.data.withdrawalFeePercentage}%</span></div></div><div className="mt-5 rounded-xl bg-[#f4faf7] p-3.5 text-xs leading-5 text-muted-foreground">MirrorX always shows the minimum and fee before you confirm a withdrawal.</div></Panel>
    </div>}
  </Shell>;
}