import { useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Filter, RefreshCw, Sparkles } from 'lucide-react';
import { useGetTransactions } from '@workspace/api-client-react';
import { CopyButton, EmptyState, ErrorState, LoadingPanel, PageHeading, Panel, Shell, StatusPill, TypeIcon } from '@/components/mirrorx-ui';

const tabs = [{ label: 'All', value: 'ALL' }, { label: 'Deposits', value: 'DEPOSIT' }, { label: 'Withdrawals', value: 'WITHDRAWAL' }, { label: 'Adjustments', value: 'ADJUSTMENT' }];

export default function Transactions() {
  const [activeTab, setActiveTab] = useState('ALL');
  const [limit, setLimit] = useState(10);
  const query = useGetTransactions({ limit });
  const rows = useMemo(() => query.data?.filter((item) => activeTab === 'ALL' || item.type === activeTab) ?? [], [activeTab, query.data]);
  const refresh = () => void query.refetch();
  return <Shell><PageHeading eyebrow="Capital ledger" title="Activity" detail="A clear trail of every movement." action={<button type="button" onClick={refresh} data-testid="button-refresh-transactions" className="inline-flex h-10 items-center gap-2 rounded-xl border border-border bg-card px-3.5 text-xs font-medium text-muted-foreground transition hover:border-[#83d9c1] hover:text-primary"><RefreshCw size={14} /> Refresh ledger</button>} />
    <Panel className="overflow-hidden" testId="panel-transactions"><div className="flex flex-col justify-between gap-4 border-b border-border px-5 py-5 sm:flex-row sm:items-center sm:px-7"><div className="flex items-center gap-2 overflow-auto">{tabs.map((tab) => <button type="button" key={tab.value} onClick={() => setActiveTab(tab.value)} data-testid={`button-filter-${tab.value.toLowerCase()}`} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-medium transition ${activeTab === tab.value ? 'bg-[#dff7ec] text-[#087f64]' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}>{tab.label}</button>)}</div><div className="flex items-center gap-2 text-[11px] text-muted-foreground"><Filter size={14} /> {rows.length} entries</div></div>
      {query.isError ? <div className="p-5"><ErrorState onRetry={refresh} /></div> : query.isLoading ? <div className="p-6"><LoadingPanel rows={6} /></div> : rows.length === 0 ? <div className="p-5"><EmptyState label="No matching activity" detail={activeTab === 'ALL' ? 'Your first deposit or withdrawal will show up here.' : 'Try another ledger filter.'} /></div> : <div className="divide-y divide-border">{rows.map((transaction) => <div key={transaction.id} className="grid grid-cols-[1fr_auto] items-center gap-4 px-5 py-4 transition hover:bg-[#f5fbf8] sm:grid-cols-[1.5fr_1fr_1fr_auto] sm:px-7" data-testid={`row-transaction-${transaction.id}`}><div className="flex min-w-0 items-center gap-3"><TypeIcon type={transaction.type} /><div className="min-w-0"><p className="truncate text-sm font-medium">{transaction.type.replaceAll('_', ' ').toLowerCase().replace(/^\w/, (letter) => letter.toUpperCase())}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{new Date(transaction.createdAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</p></div></div><div className="hidden sm:block"><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Reference</p><div className="mt-1 flex items-center gap-1"><span className="mono text-xs text-foreground">{transaction.txHash ? `${transaction.txHash.slice(0, 7)}...${transaction.txHash.slice(-5)}` : 'Internal entry'}</span>{transaction.txHash && <CopyButton value={transaction.txHash} label={`Copy ${transaction.id}`} />}</div></div><div className="hidden sm:block"><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Status</p><div className="mt-1.5"><StatusPill status={transaction.status} /></div></div><div className="text-right"><p className="mono text-sm font-medium">{transaction.type === 'WITHDRAWAL' ? '-' : '+'}{transaction.amount} {transaction.currency}</p><div className="mt-1 sm:hidden"><StatusPill status={transaction.status} /></div></div></div>)}</div>}
      {!query.isLoading && !query.isError && query.data && query.data.length >= limit && <div className="border-t border-border p-4 text-center"><button type="button" onClick={() => setLimit(Math.min(50, limit + 10))} data-testid="button-load-more-transactions" className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-xs font-medium text-muted-foreground hover:bg-secondary hover:text-foreground">Load older entries <ArrowDownToLine size={14} /></button></div>}
    </Panel>
    <div className="mt-5 grid gap-4 sm:grid-cols-3"><Panel className="p-5"><div className="flex items-center gap-2 text-[#0a9977]"><ArrowDownToLine size={15} /><span className="text-[10px] font-semibold uppercase tracking-[.14em]">Deposits</span></div><p className="mt-3 text-xs text-muted-foreground">Capital moving in is automatically reconciled.</p></Panel><Panel className="p-5"><div className="flex items-center gap-2 text-[#bd6d2e]"><ArrowUpRight size={15} /><span className="text-[10px] font-semibold uppercase tracking-[.14em]">Withdrawals</span></div><p className="mt-3 text-xs text-muted-foreground">Every outbound request is held to your limits.</p></Panel><Panel className="p-5"><div className="flex items-center gap-2 text-[#4b709d]"><Sparkles size={15} /><span className="text-[10px] font-semibold uppercase tracking-[.14em]">Adjustments</span></div><p className="mt-3 text-xs text-muted-foreground">Performance additions and internal entries.</p></Panel></div>
  </Shell>;
}