import { Link } from 'wouter';
import { ArrowUpRight, Copy, RefreshCw } from 'lucide-react';
import { useGetWalletBalances } from '@workspace/api-client-react';
import { ChainGlyph, EmptyState, ErrorState, LoadingPanel, Money, PageHeading, Panel, Shell } from '@/components/mirrorx-ui';

export default function Wallets() {
  const query = useGetWalletBalances();
  const wallets = query.data ?? [];
  const total = wallets.reduce((sum, wallet) => sum + wallet.usdValue, 0);
  const refresh = () => void query.refetch();
  return <Shell><PageHeading eyebrow="Capital map" title="Wallets" detail="Every chain, one quiet view." action={<button type="button" onClick={refresh} data-testid="button-refresh-wallets" className="inline-flex h-10 items-center gap-2 rounded-xl border border-border bg-card px-3.5 text-xs font-medium text-muted-foreground transition hover:border-[#83d9c1] hover:text-primary"><RefreshCw size={14} /> Sync balances</button>} />
    {query.isError ? <ErrorState onRetry={refresh} title="Wallet balances are offline" /> : query.isLoading ? <Panel className="p-6"><LoadingPanel rows={4} /></Panel> : wallets.length === 0 ? <EmptyState label="Your capital map is empty" detail="Connect a wallet to see balances across Solana, Bitcoin, and Ethereum." /> : <div className="space-y-5">
      <div className="grid gap-5 md:grid-cols-[.75fr_1.25fr]"><Panel className="surface-grid relative overflow-hidden bg-[#123749] p-6 text-[#e9f7f0]"><div className="absolute -right-12 -top-12 size-40 rounded-full border-[20px] border-[#b9f25b]/10" /><p className="relative text-[11px] uppercase tracking-[.18em] text-[#8eafa7]">Combined balance</p><p className="relative mt-4 text-4xl font-semibold tracking-[-.07em]" data-testid="text-wallet-total"><Money value={total} /></p><p className="relative mt-2 text-sm text-[#a9c4bd]">{wallets.length} connected network{wallets.length === 1 ? '' : 's'}</p><div className="relative mt-8 flex items-center gap-2 text-xs text-[#b9f25b]"><span className="size-1.5 rounded-full bg-[#b9f25b] animate-dot" /> Balances synced</div></Panel><Panel className="p-6"><p className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">Distribution</p><div className="mt-6 flex h-3 overflow-hidden rounded-full bg-secondary">{wallets.map((wallet, index) => <div key={wallet.id} className={`h-full ${index % 3 === 0 ? 'bg-[#15c69b]' : index % 3 === 1 ? 'bg-[#f6ad64]' : 'bg-[#769fe0]'}`} style={{ width: `${total ? wallet.usdValue / total * 100 : 0}%` }} />)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{wallets.map((wallet, index) => <div key={wallet.id} className="flex items-center gap-2"><span className={`size-2 rounded-full ${index % 3 === 0 ? 'bg-[#15c69b]' : index % 3 === 1 ? 'bg-[#f6ad64]' : 'bg-[#769fe0]'}`} /><span className="text-xs text-muted-foreground">{wallet.chain}</span><span className="mono ml-auto text-xs">{total ? Math.round(wallet.usdValue / total * 100) : 0}%</span></div>)}</div></Panel></div>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{wallets.map((wallet) => <Panel key={wallet.id} className="p-5 transition duration-200 hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)]" testId={`card-wallet-${wallet.id}`}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><ChainGlyph chain={wallet.chain} /><div><p className="font-semibold">{wallet.chain}</p><p className="text-xs text-muted-foreground">{wallet.symbol} balance</p></div></div><button type="button" onClick={() => navigator.clipboard?.writeText(wallet.id)} aria-label={`Copy ${wallet.chain} wallet identifier`} data-testid={`button-copy-wallet-${wallet.id}`} className="grid size-8 place-items-center rounded-lg text-muted-foreground hover:bg-secondary hover:text-primary"><Copy size={14} /></button></div><p className="mono mt-8 text-2xl tracking-[-.04em]" data-testid={`text-wallet-amount-${wallet.id}`}>{wallet.amount.toLocaleString('en-US', { maximumFractionDigits: 6 })} <span className="text-sm text-muted-foreground">{wallet.symbol}</span></p><div className="mt-1 flex items-center justify-between"><span className="text-sm text-muted-foreground"><Money value={wallet.usdValue} /></span><span className={`text-xs font-medium ${wallet.changePercent >= 0 ? 'text-[#0b9979]' : 'text-[#b5554c]'}`}>{wallet.changePercent >= 0 ? '+' : ''}{wallet.changePercent}%</span></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="mono text-[10px] text-muted-foreground">{wallet.id.slice(0, 8)}...{wallet.id.slice(-5)}</span><Link href="/transactions" data-testid={`link-wallet-activity-${wallet.id}`} className="inline-flex items-center gap-1 text-[11px] font-medium text-primary hover:underline">Activity <ArrowUpRight size={13} /></Link></div></Panel>)}</div>
    </div>}
  </Shell>;
}